
// Header
= Phython vs GO in functional programming
Mathias Reimann <mathias.reimann@stud.fh-rosenheim.de>
v1.00.00, 2019-01-05
:awestruct-layout: base
:showtitle:
:prev_section: defining-frontmatter
:next_section: creating-pages
:toc:
:toc-placement!:
:icons: font


= table of contents

. Introduction
. Functional programming
.. Requirements for a Functional Programming Style
... Sideeffects
... Unchangeability
... Recursion
... Higher order functions
. Explanation of the programming languages
.. GO in general
.. Python in general
. Comparison of the two programming languages
.. Functional programming in GO
... Lambda
... Map
.. Functional Programming in Python
... Lambda
... Map
... Filter
... Reduce
.. Comparison
. Conclusion
. Information sources




'''
{empty} +

== Introduction

{empty} +
For the subject "Concepts of the programming language" the two programming languages
 GO and Python shall be compared in functional programming. 
The challenge of this comparison was the learning of two new programming languages and the 
 implementation of functional programming. In this paper, the principle of 
 functional programming and its requirements are briefly presented. Afterwards 
 the two languages are briefly introduced and finally the functional applicability 
 is compared.

'''

{empty} +

== Functional programming

{empty} +
1980 the call for object-oriented programming arose. After the release of PHP 5, 
it was a good time to set new quality standards for PHP code. Away from free 
programming and confused code and towards better maintainability. 
Everything became objects.
Today it is the evolution of ECMAScript, better known under the name (functional) 
JavaScript, that brings about a trend reversal <<ECMA>>. The 2015 released version ES6 
brings countless improvements. Angular, React and Vue are the new frontend 
frameworks for web projects and apps. JS libraries like jQuery are a thing of the past.
 This change once again brings with it the call for a better code structure.
Functional programming is a programming paradigm that was developed in the 1930s and 
is based on mathematical principles. <<Funk>>

{empty} +

=== Requirements for a Functional Programming Style
{empty} +
Purely functional programming languages require pure functions. 
A pure function has the following requirements

* uses an input value
* returns the same output value
* has no side effects
* takes into account the immutability of variables
<<DefFunc>>

{empty} +

==== Sideeffects
{empty} +

NOTE: A simple side effect is, for example, storing a variable in the database. 
It is not a matter of not saving the variable, 
but of not mixing calculation and saving in one and the same function.

{empty} +

==== Unchangeability
{empty} +
NOTE: The immutability of variables is a prohibition that is not 
limited to pure functions. Variables are not changed in functional
 programming languages. Instead, a copy is created for the changed value.

{empty} +

==== Recursion
{empty} +
NOTE: Since the immutability concerns simple counters in loops, Functional Programming 
does not use for, while, do and repeat. Instead of these loop constructs 
recursion is used. In a recursion, the function calls itself again, 
and can only be stopped by an abort condition inside the function. 
<<Rec>>
{empty} +

==== Higher order functions
{empty} +
NOTE: Higher order functions can use a function as a parameter. 
Thus, it is possible to use a pure function for calculation 
in an equally pure function for storing a data set.

{empty} +

== Explanation of the programming languages
{empty} +

=== GO in general
{empty} +

In 2007, the three Google developers Robert Griesemer, Rob Pike and Ken Thompson 
named goals that should lead to an optimized and especially simplified 
programming language. With these considerations the foundation for GO and Golang 
was laid. Google drove the development of the ambitious project by providing 
the necessary resources. Since GO 2011 was declared an open source project (BSD license), 
a large community has been working to improve the programming language.
The motivation for the development of a new programming language is due in 
particular to dissatisfaction with various established programming languages. 
Until now, these languages were characterized by the fact that aspects such as 
efficient code compilation, fast code execution or a simple programming process 
could not be executed simultaneously.
With the development of Golang, however, it was possible to integrate several advantages. 
On the one hand, this is compilable, whereby the focus to this day is on a high 
translation speed. In addition, when the programming language is used, automatic 
memory cleanup runs in the background to optimally manage memory resources and 
prevent memory problems. Golang is now used by developers worldwide, 
and is very mature and stable despite short development time. 
Especially the simplicity and multifunctionality of the language is 
appreciated by the developers.


'''
{empty} +

=== Python in general
{empty} +
Python was developed in the early 1990s by Dutchman Guido van Rossum at the 
Centrum voor Wiskunde en Informatica (CWI) in Amsterdam. Originally Python 
was intended as a scripting language for the distributed operating system Amoeba. 
He thus created a programming language that was powerful and at the same 
time simple and easy to learn. The name Python is not based on the snake-like name, 
but pays homage to the British comedy troupe Monty Python <<Guido>>. Guido van Rossum 
recently worked for Google, where he spends half of his working time developing Python 
further <<Guido2>>. Basically, a Python program consists of individual instructions that, 
in the simplest case, occupy exactly one line in the source code. Python is both an
interpreted and a compiled language. Python code is translated into intermediate 
code that must be executed by a virtual machine known as PVM, the Python virtual 
machine. This is a similar approach to Java.

{empty} +
== Comparison of the two programming languages
{empty} +

This section compares the two languages GO and Python in functional programming.

{empty} +

=== Functional programming in GO 
{empty} +
The following examples describe Functional Programming in GO.
<<GoFunctions>>
{empty} +

==== Lambda

.lambda.go
[source,golang]
----
package main

import "fmt"

func slowFilter(whitelist ...int) func(int) bool {
    return func(x int) bool {
        for _, value := range whitelist {
            if value == x {
                return true
            }
        }
        return false
    }
}
----


As shown in the code example above it is possible to create anonymous functions in GO, 
also called Lambda function. A lambda function is defined in this language
as an unnamed method. In GO this can be created simply with "func(input value) 
output value". As in the slowFilter function, this is integrated into a Closure function
This means that the inner function can access the variables of the outer function 
while the outer function depends on the inner function. This combination creates a 
closed method. The creation of a closure requires much less work than the 
creation of a class with only one method. Following an object-oriented view, 
closures are thus suitable for the rapid creation of an object-like structure 
without a class. Often an anonymous function is used as the inner method.

{empty} +

==== Map

.map.go
[source,golang]

----
func fastFilter(whitelist map[int]bool) func(int) bool {
    return func(x int) bool {
        if whitelist[x] {
            return true
        }
        return false
    }
}
----

The map functionality in Golang mapped key values and associated values. 
The map function can be called by the make function and returns an initialized map.
This functionality is faster and cleaner than a list which has to be filled manually 
with values via a loop.

'''
{empty} +

=== Functional Programming in Python

To quote the inventor of Python, Guido van Rossum, Functional Programming in Phyton 
was introduced by a Lisp hacker and will no longer be integrated into Python 
Version 3. Since it could not assert itself, it is still possible today to 
program functionally in Python.
The following functionalities are possible in relation to functional 
programming in Python.
<<PyFunctions>>
{empty} +

==== Lambda
The lambda functions are marked in Python with the expression "lambda". 
The difference to normal functions is that they do not have to be defined separately.

.lambda.py
[source,python]
----
#lambda function
lambdaAddition = lambda x, y : x + y
lambdaAddition (1,1)

#normal funciton
def addition(x,y):
    return (x+y)

addition(1,1)
----

The lambda syntax makes the code more readable and easier to test. 
This also ensures the cancellation of side effects. 

{empty} +

==== Map
A map function is defined in Python as "map(function, sequence)".  
Map applies a function to process a sequence and returns a list with the 
result. To execute it cleanly and legibly it is often combined with a 
lambda function.

[source,python]
----
#map with lambda
list(map((lambda x: x **2), items))
----

{empty} +

==== Filter

The function filter(function, list) offers an elegant way to 
filter out those elements from the list for which the function returns True.

.filter.py
[source,python]
----
#map with lambda
list(map((lambda x: x **2), items))
----

{empty} +

==== Reduce
Sequences can be reduced in Python. This can be done with the 
reduce(function, sequence) function.

.reduce.py
[source,python]
----
#reduce with lambda
reduce(lambda x,y: x+y, [47,11,42,13])
----

The Reduce procedure in this example adds the first two contents of the sequence 
and writes them back to the first position of the sequence and deletes the second one. 
Thus all values are added together and 113 is written as result.

'''
{empty} +

=== Comparison

In the direct comparison of the functional programming in GO and Python Python 
delivers additionally a reduce and filter functionality. Thus Python provides more 
functions than GO, which do not have to be programmed by the user. 

.Functional compares
[width="30%"]
|=========
|Go|python 

| 
[x] Lambda 

[x] Map

[ ] Filter

[ ] Reduce


| 
[x] Lambda 

[x] Map

[x] Filter

[x] Reduce

|=========



Since the effort for reduce and filter is not very complex, see Figure 3, this 
can only be included to a limited extent in the evaluation. Furthermore Python 
is a long existing language and there are many sources for functional programming 
to get tips or ready-made solutions. The advantage of GO is the Lambda functions, 
because this does not have to be marked explicitly and therefore less writing effort 
is required. In addition, a clean code is created that is easier to read.  
The readability of the code is also given in Python because Python should be 
programmed according to the principle "One line, One function".
The speed of Go compared to Python should be especially emphasized. 
For more complex mathematical functions, like a prime factorization, Go is much faster.
In the example below, Go needs only a third of the time python takes.
<<WhyGo>>

.prime.py
[source,python]
----
from itertools import chain

def is_prime(n):
  if n == 2 or n == 3: return True
  if n < 2 or n%2 == 0: return False
  if n < 9: return True
  if n%3 == 0: return False
  r = int(n**0.5)
  f = 5
  while f <= r:
    print '\t',f
    if n%f == 0: return False
    if n%(f+2) == 0: return False
    f +=6
  return True
----



.prime.go
[source,golang]
----
package main
import "math"

func main() {
	var limit uint = 100000
	var zahl, zaehler uint
	var primzahl bool
	for zahl = 2; zahl <= limit; zahl++ {
		primzahl = true
		for zaehler = 2; zaehler <= zahl/2; zaehler++ {
			if math.Mod(float64(zahl), float64(zaehler)) == 0 {
				primzahl = false
				break
			}
		}
		if primzahl == true {
			println(zahl, " ist eine Primzahl")
		}
	}
}
----


'''
{empty} +

== Conclusion
To really want to program functionally, most forums refer to languages 
like Scale and Lisp. Haskell is also a term that can be read frequently. 
In comparison of the programming languages Python and GO I would prefer GO, 
because the syntax is more similar to the programming languages I know. 
GO also stands out because of its speed, as the language is compiled. 
The compilation process also shows errors in advance, which Python only 
detects at runtime. Also that there is a debugger is an advantage in some cases. 
Since the Python debugger works with its own syntax again, I was able to achieve 
faster programming progress in GO. 

'''
{empty} +

== Information sources
{empty} +


Func:[[Funk]] https://de.wikipedia.org/wiki/Funktionale_Programmierung#Funktionale_Programmiersprachen

DefFunc:[[DefFunc]] https://jaxenter.de/funktionale-programmierung-77390

PyFunctions:[[PyFunctions]] https://www.python-kurs.eu/lambda.php

WhyGo:[[WhyGo]] https://hackernoon.com/5-reasons-why-we-switched-from-python-to-go-4414d5f42690

GoFunctions:[[GoFunctions]] https://blog.golang.org/go-maps-in-action

Guido:[[Guido]] https://de.wikipedia.org/wiki/Guido_van_Rossum

Guido2:[[Guido2]] https://gvanrossum.github.io/Resume.html

ECMA:[[ECMA]] https://en.wikipedia.org/wiki/ECMAScript

Rec:[[Rec]] Book: Logic, Sets, and Recursion, Side: 227, From Robert L. Causey, Second Edition

