= Compare Go Distributed Programming with Scala
Maximilian Zelles
Fakultät Informatik

== 1. Introduction
Distributed systems are difficult to develop because they depend on many components. A reliable and highly secure network is assumed, in which the topology of the computing realm does not change. In fact, you need an administrator to manage the whole system. Scala and Go are very important languages in the development of distributed systems. Time is changing, computers are getting smaller and more powerful. Security also plays a major role in computer science. The smartphone is the result of years of research. These devices are packed with sensors, lots of memory and a powerful CPU. They are nothing less than full-fledged computers. Nowadays it is even possible to put together a computer system that consists of many networked computers, big or small. These computers are usually geographically distributed, which is why they are said to be a distributed system. The connection network may be wired, wireless, or a combination of both. In addition, distributed systems are often very dynamic, meaning that computers can join and leave, with the underlying network's topology and performance changing almost constantly.

== 2. General Information
This chapter describes the programming language Go and its usage. What are the reasons for developing a new language like Go and what are the advantages in using this language? Then the programming language Scala is presented, for which reasons it was developed, for which application this language is of advantage. Furthermore, the definition of distributed programming is explained. It deals with distributed systems and their application, the problems with the development of distributed programs and the types of communication technologies.

=== 2.1 The programming language - Go
Go is an opensource project, developed by Google. Go is a simple but powerful programming language, which also makes fun to work with. It is a compiled, concurrent, garbage-collected, statically typed language.

The programming language was introduced in 2007 as the answer to some of the problems with the developing infrastructure at Google. The actual computing landscape is independent to the environment in which the language is being used (mostly C++, Java, Python). With these programming languages a lot of problems like multicore processors, networked systems, massive computation clusters, and the web programming model were being worked around rather than addressed head-on. Moreover, the scale has changed: todays server programs have more then million line of code, will be developed by thousands of developers every day, so that build time have stretched to many minutes up to many of hours.

Go was designed and developed to make the work more comfortable and more productive. There are a lot of built-in concurrency and garbage collection. The design of this language includes dependency management, the adaptability of software architecture as systems grow and robustness across the boundaries between the components.

=== 2.2 The programming lanugage - Scala
The design of Scala started in 2001 at a research institute in Switzerland. It should be a programming language combining the ideas from functional programming and Petri net. Petri net is also known as a place/transition net and is one of several mathematic modeling languages for the description of distributed systems. So, this will also very important for distributed programming, but you can read in the following comparison in capture three. Before the founder worked a lot at java and java’s compiler. Officially Scala gets released on the Java platform in 2004, a second version follows in 2006.

Scala is a general-purpose computer language, with a big view on functional and object-oriented programming style into an extremely concise, logical, and extraordinarily powerful language. This language is not the only attempt to create a better language like Java, but they made the fundamental decision to remain very close in syntax to the Java. This language has influenced by the Java programming language. Sala language is a strong static type of programming language which has a multiple possibility for usage. I can be used to write web applications, desktop applications, mobile applications and so on. Huge benefits on developing with Scala is, that it takes less time to code as compared to Java. 

=== 2.3 Definition of Distributed Programming
A distributed system is a system whose components are located on different networked computers, which then communicate and coordinate their actions by passing messages to one another. A computer program that runs in a distributed system is called a distributed program, and distributed programming is the process of writing such programs. In the time everything started, the word “parallel” has a different meaning than it has nowadays. The time before the context of parallel means the distributed geographically and physical located computers. Nowadays its referring to autonomy processes, that run in the same physically computer. 

A distributed program defines different components, which are communicating with other components in the distributed system and their users. But there are also problems in programming a distributed application. There are two low-level API’s for every operating system necessary. First is the network access, this is being done with sockets and parallelism, which is being done with threads/processes. For example, in the low-level, the evaluation of the return values for every operating system call. Another one is the missing type-safety in the UNIX-Socket API. Another one is handling parallelism with semaphores and monitors. There is also a very complex implementation of the necessary high-level concept, like finding the right component in the network or the handshake between the communication partners. And there are problems with scaling up to many users, because the operating systems APIs has a missing resource management. For example, a Unix process allows only seven open network connections, so there are just less of processes per computer available. Middleware is being used, to give the low-level APIs in the operating system more functionality. The middleware is called a service in the computer to hide the complexity of the underlying applications and infrastructure. There are different types of communication technologies. One of them is a socket connection. Earlier its being used for network programming with Unix. It’s a synchronous connection-oriented exchange of byte streams or asynchronous connectionless exchange of datagrams (packages) with barely defined protocols. Another one is the Remote Procedure Call. This removes the method/procedure calls while accessing on resources (like REST API). Typically, its technically synchronized in the Request/-Reply-Style.


== 3. Comparison of distributed programming
This chapter describes the comparison between both languages on sockets and remote procedure calls. First, the server-side socket is shown in Go, then the client side. Thereafter, sockets are shown in Scala using a server client example. Finally, RPC will be compared in GO and Scala. Also, a server and client example are used to show differences better. 

=== 3.1 Developing Sockets in Go
Sockets are one of the basic techniques for network programming. Raw-Sockets are sockets, which also allow the programmer to build their own IP protocol or use protocols other than TCP or UDP. These two are not the only ones built above the IP layer. Go allows to create Raw-sockets, to communicate with another protocol or to create your own protocol. It just supports it minimal, so it allows to connect hosts and send packages between them. 

The following example shows a TCP network stack processing overhead of Go. In the pictures below, there can be seen a simple “ping-pong” client and server example in Go. In the first picture is the server-side code.

[source, Go]
----
import ( "net" "runtime" )

func handleClient(conn net.Conn) { defer conn.Close()

	var buf [4]byte
	for {
		n, err := conn.Read(buf[0:])
		if err!=nil {return}
		if n>0 {
			_, err = conn.Write([]byte("Pong"))
			if err!=nil {return}
		}
	}
}

func main() { runtime.GOMAXPROCS(4)

	tcpAddr, _ := net.ResolveTCPAddr("tcp4", ":1201")
	listener, _ := net.ListenTCP("tcp", tcpAddr)

	for {
		conn, _ := listener.Accept()
		go handleClient(conn)
	}
}
----

The program starts in the main function where the IP address and the open port on which the server is reachable, will be defined. In the for loop, the server is accepting the clients, they are connecting to this IP address and port. On the client side, a maximum number of pings is set, how often the client is allowed to request the server. In the ping function, an attempt is made to contact the server with the corresponding IP address and the port and to send the string "ping". The server responds with the string "Pong" as soon as it has received a string from the client. Then the connection is closed.

[source, Go]
----
import ( "net" "fmt" "time" "runtime" )

func ping(times int, lockChan chan bool) { tcpAddr, _ := net.ResolveTCPAddr("tcp4", "localhost:1201") conn, _ := net.DialTCP("tcp", nil, tcpAddr)

for i:=0; i<int(times); i++ {
	_, _ = conn.Write([]byte("Ping"))
	var buff [4]byte
	_, _ = conn.Read(buff[0:])
}
lockChan<-true
conn.Close()    
}

func main() { runtime.GOMAXPROCS(4)

	var totalPings int = 1000000
	var concurrentConnections int = 100
	var pingsPerConnection int = totalPings/concurrentConnections
	var actualTotalPings int = pingsPerConnection*concurrentConnections

	lockChan := make(chan bool, concurrentConnections)

	start := time.Now()
	for i:=0; i<concurrentConnections; i++{
		go ping(pingsPerConnection, lockChan)
	}
	for i:=0; i<int(concurrentConnections); i++{
		<-lockChan 
	}
	elapsed := 1000000*time.Since(start).Seconds()
	fmt.Println(elapsed/float64(actualTotalPings))
}
----

=== 3.2 Developing Sockets in Scala
This chapter also establishes a socket connection between a server and a client. This time not in the Go language, but in Scala. As you can see in the example below, a server is created that defines port and IP address. The ip address is localhost because the server is running on a local machine. As in Go, the server in Scala waits for a request from the client (this is done with the while (true) loop). As soon as a request to connect the client comes, the connection is accepted and the server calls the function "Handle Client", in which data is received and sent.

[source, Scala]
----
object main{

	def handleClient(s: Socket) : Unit = {
		val in = s.getInputStream
		val out = s.getOutputStream
		while(s.isConnected){
			val buffer = Array[Byte](4)
			in.read(buffer)
			out.write("Pong".getBytes)
		}
	}

	def main(args: Array[String]){
		val server = new ServerSocket(1201)
		while(true){
			val s: Socket = server.accept()
			future { handleClient(s) }
		}
	}
}
----

In the picture below, you can see the code for the client. Again, a maximum number of pings is set. Futures provide a way to reason about performing many operations in parallel– in an efficient and non-blocking way. So, if a connection gets accepted, the function “ping” will be called. The client connects to the server with the address “localhost” and the port 1201. OutputStream is used to convey a string to the server, InputStream is used to receive a string. In this case, the client first writes “Ping” to the server and after that reads something from the server. It will be “Pong”, what will be sent from the server to the client. 

[source, Scala]
----
object main{

	def ping(timesToPing: Int) : Unit = {
		val socket = new Socket("localhost", 1201)
		val out = socket.getOutputStream
		val in = socket.getInputStream
		for (i <- 0 until timesToPing) {
			out.write("Ping".getBytes)
			val buffer = Array[Byte](4)
			in.read(buffer)
		}
		socket.close
	}

	def main(args: Array[String]){
		var totalPings = 1000000
		var concurrentConnections = 100
		var pingsPerConnection : Int = totalPings/concurrentConnections
		var actualTotalPings : Int = pingsPerConnection*concurrentConnections

		val t0 = (System.currentTimeMillis()).toDouble
		var futures = (0 until concurrentConnections).map{_ => 
			future(ping(pingsPerConnection))
		}

		Await.result(Future.sequence(futures), 1 minutes)
		val t1 = (System.currentTimeMillis()).toDouble
		println(1000*(t1-t0)/actualTotalPings)
	}
}
----

=== 3.3 Comparing Sockets between Go and Scala
When implementing both sockets in the respective languages, no major differences were noticed. The code looks very similar. Both implementations are very naive and there is probably room for improvement, but the actual code has more functions for a better error handling. The Client starts a defined amount of persistent concurrent connections to the server and makes a defined number of pings (just the String “ping”), to each the server responds with the String “pong”.

To compare the performance, the experiment where performed on a 2,7 GHz quad core MacBook Pro, Client and Server running locally. There will be 100 Clients connecting to the server with around 1 Million Pings to the server evenly distributed over the connections. This test is from 2013, currently Scala was a bit faster then go with an average round trip time of 1.6 microseconds. Go needed 11 microseconds. Of course, Go is really fast, but if a software is taking a TCP packet and passing on to another endpoint, this can make a huge difference in maximum throughput. 

Very notable is the memory size of Go with only 10MB. Scala nearly needs 200MB.


=== 3.4 RPC and GRPC with Go
A remote procedure call (RPC) results, when a computer program in distributed computing creates a call to a component in a different address space. Mostly it’s a computer in a shared network. It’s an interface to start different procedures on remote computers. The RPC is based on the UDP or TCP protocol and represents a frequently used technique for the realization of client / server architectures. It enables application to call functions on another process or machine. Every major language has proprietary RPC frameworks. Go’s RPC framework is called: Go-net.rpc Googles RPC (GRPC) is a language independent RPC based on protocol buffers. Native implementations are available for Go, Java and C++. 
[source, Go]
----
type Response struct {
	Message string
}
type Request struct {
	Name string
}
type Handler struct {}

func (h *Handler) Execute(req Request, res *Response) (err error) {
	if req.Name == "" {
		err = errors.New("A name must be specified")
		return
	}

	res.Message = "Hello " + req.Name
	return
}

rpc.Register(&core.Handler{})

listener, _ = net.Listen("tcp", ":"+strconv.Itoa(Port))

defer listener.Close()

rpc.Accept(listener)
----

If the handler has been defined, creating the server is very easy, for someone has set up an HTTP or TCP server before. There is just one difference, before actually listening for incoming connections, you have to call rpc.Register and pass the service handler as you can see in the upper picture. Then a TCP Listener will be created, that will listen on a specific port. The defer statement defers the execution of a function until the surrounding function returns, so it will be stopped, whenever someone stops it. In line 27 the server is waiting for incoming connections and accepts it. The next picture shows the client side.

[source, Go]
----
var (
        addr     = "127.0.0.1:" + strconv.Itoa(Port)
        request  = &core.Request{Name: Request}
        response = new(core.Response)
)

client, _ = rpc.Dial("tcp", addr)
defer c.client.Close()

_ = c.client.Call(core.HandlerName, request, response)
fmt.Println(response.Message)
----

On the client side there will be defined the address of the server, the request and the response. Then there will be tried to connect to the server with the address, that is defined at the top. Same like on server side, with defers, the connection will be closed. At the bottom of the picture there will be created a call to the server, the response will be shown with the statement in the last line. 

=== 3.5 RPC and GRPC with Scala
In Scala it’s the procedure of RPC is similar. The LoggerAPI and FooRepositoryAPI will be defined to share interfaces and fields between classes (in this case – server and client). Client and server can communicate over statically typed interfaces like below. On server side the server implements the functions from the LoggerAPI and FooRepositoryAPI tells the functions, what to do. The Server binds both API’s when it gets started. There is a function, that waits for a request and receives it. If a request gets sent, the server answers a response.  
[source, Scala]
----
rait LoggerAPI {
  def log(message: String): Unit
}

case class Foo(id: String)

trait FooRepositoryAPI {
  def add(foo: Foo): Future[Unit]
  def remove(foo: Foo): Future[Unit]
  def getAll(): Future[Set[Foo]]
}

class LoggerAPIImpl extends LoggerAPI {
  override def log(message: String): Unit = println(message)
}

class FooRepositoryAPIImpl extends FooRepositoryAPI {
  var foos: Set[Foo] = Set()

  override def add(foo: Foo): Future[Unit] = this.synchronized {
    foos = foos + foo
    Future() // Acknowledge
  }

  override def remove(foo: Foo): Future[Unit] = this.synchronized {
    foos = foos - foo
    Future() // Acknowledge
  }

  override def getAll(): Future[Set[Foo]] = Future {
    foos
  }
}

val jsonSerializer = // ...
val server = JSONRPCServer(jsonSerializer)
server.bindAPI[LoggerAPI](new LoggerAPIImpl)
server.bindAPI[FooRepositoryAPI](new FooRepositoryAPIImpl)

def onRequestJSONReceived(requestJSON: String): Unit = {
  server.receive(requestJSON).onComplete {
    case Success(Some(responseJSON: String)) => sendResponseJSONToClient(responseJSON)
    case _ =>
  }
}
----

On client side, there will be defined a client, also creating both Interfaces with the function “createAPI”. So they are possibel to use the functions. There will be just added and removed some Letters for testing. To receive all foos, the client calls the API, gets all Elements and shows them. There is also a “onResonse…” function, that listens, if the client gets a response and recieves this. 

[source, Scala]
----
val jsonSerializer = // ...
val jsonSender = // ...
val client = JSONRPCClient(jsonSerializer, jsonSender)

val loggerAPI = client.createAPI[LoggerAPI]
val fooRepositoryAPI = client.createAPI[FooRepositoryAPI]

loggerAPI.log("Hello, World!")

fooRepositoryAPI.add(Foo("A"))
fooRepositoryAPI.add(Foo("B"))

fooRepositoryAPI.remove(Foo("A"))

fooRepositoryAPI.getAll().onComplete {
  case Success(foos: Set[Foo]) => println(s"Received all the foos: $foos")
  case _ =>
}

def onResponseJSONReceived(responseJSON: String): Unit = {
  client.receive(responseJSON)
}
----


== 4. Conclusion
Both languages are very powerful and very similar in distributed programming. Setting up a simple client server socket connection is easy with both languages. The Princip how the workflow goes, is the same. Starting a server on a specific port and waiting for a connection. If a connection request is incoming, the server accepts and handles the client (sending some strings). The Client starts a connection on the servers IP address and the specific port, on which the server is listing. There is defined a number of total pings and current connections. 

Using the remote procedure call is a bit different in both languages, but not that much. In Go its very easy to set up a rpc, if someone had set up a socket before. There is just one difference, to register the handler at the rpc. 

In Scala the remote procedure call will use interfaces, that are implemented on server side. There will be something used, that is called trait. Traits are used to share interfaces and fields between classes. The server binds the Implemented APIs and waits for a request. The client uses that trait as well and is able to functions like add, remove or getAll. 

Different techniques in using remote procedure call, but the same idea behind that.