= Functional Programming: Go vs. Elixir
by Lukas Buchner
v1.0, 2019-05-01
:highlightjsdir: highlight
:stem:

== Introduction
During the last decades the functional programming paradigm has become a lot more popular and respectable. 
Thus language designers tend to incorporate functional features into their programming languages. 
In this paper, I try to shed some light on how the programming languages Golang and Elixir approach functional programming. 
The considered versions of the languages are Golang 1.11.4 and Elixir 1.7.4. +

Go, often referred to as Golang, calls itself a multiparadigm language. 
It is a young language, originating in the last decade. 
Go focuses on simplicity and building reliable and efficient software. 
With a nice abstraction, it gives easy access to concurrency and thus utilizing modern processors.
Optically it has an undenieable touch of C. 

Elixir is a young language as well, appearing the first time in 2011. 
It calls itself a dynamic, functional language designed for building scalable and maintainable applications. 
Elixir runs on the Erlang VM BEAM, known for running low-latency, distributed and fault-tolerant systems. 
By design it is interoperable with Erlang, allowing Elixir to leverage the Erlang ecosystem.

Now what is functional programming, anyway? 
----
It is a programming paradigm, where computation is based on the combination of pure functions. 
Using this paradigm avoids shared state, mutable data, and side effects. 
In contrast to the imperative paradigm, functional programming follows a declarative approach. 
----

Note, that many of todays languages are being called functional despite not adhering to this definition. 
Most languages out there are not pure, which has a massive impact on the assumptions that can be made about a program. 
Calling a language functional usually just indicates it incorporates some of the functional ideas.  

== Lambda Calculus
A myriad of buzzwords and complicated mathematical ideas revolve around functional programming. 
However, the essence of these languages is way simpler. 
Apparently, almost all functional languages share a common ancestor, the lambda calculus. 
Introduced as a computational model by the mathematician Alonzo Church in the 1930s, it does not dictate any of the modern languages' features a necessity. 
In fact, its ruleset could barely be simpler. 
The Lambda Calculus allows to define functions, apply them and then compute them (obivously the idea is a little more complex than that, but no deeper knowledge is needed to understand this paper, thus the simplification) <<LC>>. Let us have a look at how the languages handle these scenarios:

.main.go
[source, go]
----

func add(x, y int) int { // <1>
	return x + y
}

func eval(fun func(int, int) int, x, y int) int { // <2>
	return fun(x, y)
}

eval(add, 5, 10) // --> 15 // <3>

----

<1> Defines a function in Go
<2> Defines a function that takes another function as parameter. The lambda calculus allows this implicitly.
<3> Applies a function and computes the result

.main.exs
[source, elixir]
----

defmodule Calc do
  def add(x, y), do: x + y  //<1>
  def eval(fun, x, y), do: fun.(x, y) //<2>
end

Calc.eval(&Calc.add/2, 5, 10) # --> 15//<3>

----

<1> Defines a named function in Elixir
<2> Defines a named function, which takes a function as parameter. 
<3> Applies a function and computes the result. The *&* is used to pass a function defined in a module as a parameter whereas the */* denotes its arity. In this case the function *add* is of arity 2 as it does take two parameters.

Both languages provide toolkits allowing the same things as the lambda calculus, which makes them equally powerful. 
Apparently, the Lambda Calculus is equivalent in computational power to the Turing machine.  
So, in theory, we could end here agreeing that both languages on a low-level basis provide everything needed for functional programming. 
However for a programming language to be practical for humans a lot more needs to be taken into consideration.

== Type Systems

Go is a compiled language with a static type system. Thus all types of a program are known at compile time. In case types are not compatible the compiler will gladly let you know:

[source, go]
----

func isTrue(b bool) bool {
	return b
}

isTrue(10) //<1>
----

<1> compiler returns: cannot use 10 (type int) as type bool in argument to isTrue

How about writing a function, that always returns the passed parameter, known as the Id function. That should be easy, right?

[source, go]
----
func id(x interface{}) interface{} { //<1>
	return x
}

id(10).(int) //<2>
id(true).(int) //<3>
----
<1> Go lacks support for parametric polymorphism. To be generic, one has to use the empty *interface{}*, which may contain anything.
<2> Calls *id* with an integer. Returns the *interface{}* and has to be cast to an integer. 
<3> Compiles without errors, but raises a panic at runtime as the cast cannot be performed. 

Already it is a hassle working with the *interface{}*. 
With this simple example, the programmer has lost compile-time safety as Go surrenders once it encounters the use of *interface{}*. 
One might argue, the *id* function is barely used other than for demonstration purposes. 
So, how about a key concept of functional programming: functional composition. 
Functional composition allows you to combine a number of functions to form a new one. 
Hereby the result of one function is passed as the argument to the next one.

[source, go]
----
//just for improved readability
type any interface{}
type function func(any) any

func compose(g, f function) function {
	return func(x any) any {
		return g(f(x))
	}
}
//needs this type declaration, otherwise, it cannot be passed to compose
func pow2(x any) any { 
	return x.(int) * x.(int)
}
 //needs this type declaration, otherwise, it cannot be passed to compose
func sqrt(x any) any {
	return math.Sqrt(float64(x.(int)))
}

same := compose(sqrt, pow2) //first copute pow2, then sqrt with result of pow2
same(12392)     //--> 12392
----

Here the problem becomes obvious. 
For being polymorph the compose function takes two functions that take *interface{}* as parameter. 
As a consequence, every function that strives to be composable has to adhere to the type signature with *interface{}*. 
This leads to the loss of compile-time safety a static type system provides. 
Furthermore, readability suffers as the empty *interface{}* by itself does not allow any reasoning about used types, which is fundamentally different to parametric polymorphism.
In fact, when writing Go this way the type system has become more of a burden than being actually useful. +

Elixir uses different concepts than Go. 
It is a dynamically typed language, which means all types of a program are inferred by the runtime. 
Although it is dynamically typed, Elixir supports strict type checks for operators. 

.main.exs
[source, elixir]
----
hype = "Elixir is awesome"
awesomeness = 42
hype + awesomeness # This is an error
----

In this example two variables were defined, one of type string and one of type int. 
The *+* operator requires both sides to be of type int. 
This compiles with a warning, but will result in the following error at runtime: 

----
warning: this expression will fail with ArithmeticError
  main.exs:3

** (ArithmeticError) bad argument in arithmetic expression
    main.exs:3: (file)
    (elixir) lib/code.ex:767: Code.require_file/2
----

So far so good. Let's head to our Id function. 

[source, elixir]
----
id = fn a -> a end //<1>
id.("some") #--> "some" //<2>
----

<1> Defines an anonymous function in Elixir and binds it to a name. 
<2> Calls the the *id* function. The *.* is necessary, as Elixir differentiates between named and anonymous functions. 

Writing this function is a breeze in Elixir compared to Go. 
It supports all types and works without casting. 
Let us next define the compose function: 

[source, elixir]
----
compose = fn(g, f) -> 
            fn(arg) -> g.(f.(arg)) end 
          end
pow2 = fn(x) -> x * x end
sqrt = fn(x) -> :math.sqrt(x) end #uses the erlang math library

same = compose.(sqrt, pow2)
same.(10) #--> 10.0
----

This just looks like an improved version of the Go code. 
Without the types and braces, the Elixir code has a less cluttered look to the eye. 
Another big bonus is the absence of casting, which again improves readability and allows for better function reuse. 
Last, the signature of the composed functions stays natural, whereas the Go version forced functions to be defined with *interface{}*. 
It is fair to say, that elixir allows the more elegant functional code due to more concise syntax and the absence of types. 
However, as a consequence, there is no compile-time safety and hence nothing preventing you from composing nonsense. 
Same holds true for Erlang and the underlying Beam VM. 
This design decision led to criticism and requests for a strict type system. 
Apparently, there was an attempt to integrate this request without breaking the Erlang ecosystem, which failed for several reasons.  
As a result, the request was solved in a different way.
Erlang now provides a tool called "Dialyzer", which performs static type analysis. 
Elixir uses the same tool to solve the exact same problem. 
A programmer can optionally provide type specifications for functions. 
Dialyzer will then analyze whether functions are called with wrong arguments in the code. 
With this technique, Elixir tries to combine the best of the dynamically and strictly typed worlds. 
You get the feel of a dynamically typed language plus most of the security a strict type system provides. 

== Immutability
Immutability is a well known principle in programming in general, but especially popular in functional programming languages. 
An object is called immutable if it guarantees there is no possibility to modify its values. 
Hence a reference to that object guarantees to always point to the same value. 
Immutability offers some welcome advantages, such as thread safety and improved reasoning about written code. 
Before we dive into Elixir and Go a few terms need to be defined.

A *reassignment* occurs if a variable's reference can be rebound to point to a different object. 
This is not a mutation, as the previously pointed to object is left unchanged. 
Few languages are driven by strict non-assignability, which prohibits the reassignment of variables. 
Instead, most languages allow references to change. 
More important is whether the immutability guarantees for an object are *deep* or *shallow*. 
For *deep* immutability all object's fields must be non-reassignable and transitively-referred to objects have to be immutable as well. 
In contrast, *shallow* immutability forbids the reassignment of an object's fields but allows for transitively referred to objects to be mutated. 
From a clients perspective the deep immutablity guarantees are preferable. <<IM>>

In Elixir all data guarantees deep immutability. 
In general, this means whenever a structure shall be modified, a new object with the modified values is the result. 
Note that Elixir internally handles this case differently depending on the type of updated object. 
For more details please head to the Elixir documentation. 
For the reassignment part: Elixir allows to bind a label to a value. 
The word label is used on purpose, as the standard term variable tends to confuse here. 
Attaching a label in Elixir actually means the left-hand side is interchangeable with the right-hand side of the expression. 
For mutable objects in other languages this is not true, thus the differentiation between variables and labels. 
Unlike Erlang those labels can be shadowed and even be rebound, as shown below:   

[source, elixir]
----
a = "now"
x = a
a = "later" #rebinding a
# a is "later", x is "now"

shadow = fn b -> 
#Here the outer a gets shadowed by the inner a. Outer a is inaccessible
              a = "see you " 
              a <> b
          end 
shadow.(a) # --> "see you later"
# a is still "later"
----

Go by itself does barely make any guarantees at all. 
However, it provides language features that enable immutability to some extent. 
Some basic types of Go are immutable, such as numbers, booleans, and strings (and a bunch more).
The standard container types such as maps or arrays/slices are mutable. 
Let us have a look at the easiest language feature for immutability: const. 

[source, go]
----
const Pi = 3.14  //This can never change
----

Meant for defining constants, *const* is a keyword of the Go language. 
This can only be used in conjunction with the types of character, string, boolean, or numeric values. 
Obviously this restriction makes *const* a bad choice for guaranteeing immutability. 
Let us explore the next option: pointers. 
Go features pointers, which give the programmer control about the way values are passed to functions. 
With this at hand, it is possible to build functions which take parameters call-by-value.
Hereby the function receives an actual copy of the object. 
This effectively makes it impossible for the function to mutate the state of the object referenced from the outer scope. 
In contrast, using a pointer, and therefore call by reference, the function can mutate the state of the object having an effect in the outer scope. 
Using this technique allows to design immutable data types, as the following example illustrates: 

[source, go]
----
package rational 

//represents a rational number with numerator/denominator
//fields start with a lowercase letter, thus cannot be accessed from outside this package
type Rational struct {
	numerator   int  
	denominator int
}

func NewRational(numerator int, denominator int) Rational {
	//creates a new Rational number 
}

//Call by value, cannot mutate object
//returns a NEW Rational object
func (x Rational) Multiply(y Rational) Rational { 
	return NewRational(x.numerator*y.numerator, x.denominator*y.denominator) 
}  
----

The above pattern shows how to implement immutable data structures in Go. 
All of its methods are read-only and never mutating. 
This can be ensured by using call-by-value for function parameters.
In case of modification new objects get created. 
Unfortunately, this pattern cannot guarantee immutability entirely, as the struct fields may be used from within the same package. 
So, the package developer has to make sure not to mutate the object as Go does not allow any further restrictions. 
The last option Go offers is to create manual copies of the objects. 
Unfortunately, this obfuscates the code for the sake of immutability and adds runtime overhead. 
To sum up, Go was not designed with immutability as paramount and exactly feels that way. +
It does not help the developer to make any assumptions nor guarantees. 
Based on that, almost no library was written with immutability as a major concern. 
However, it follows, a libary's client can only be pessimistic and assume mutability. 
So even if your part of the program is strictly immutable, you lose most of the safety when calling into a library. 

== Purity

Purity is a concept that applies to functions. 
A function is called pure if the two rules apply: 

. The function depends on its arguments only and is idempotent. 
This also excludes mutable references and things such as I/O streams. 

. The function has no side effects, which means the evaluation does not involve any mutation.
Note, this also applies to effects appearing to the outer world like I/O.  

If both rules apply, the function is a computational analog of a mathematical function. 
A few programming languages have been designed around the principle of purity, such as Haskell. 
In pure languages, the entire program fulfills the principles of purity. 
As I/O is inherently impure, a pure programming idiom, the I/O Monad, was found for pure functional programming. 
However, neither Go nor Elixir are designed to be pure languages. 
For Golang this can be determined easily when remembering the Immutability chapter. 
Go does not offer any Immutability guarantees and leaves this decision to the programmer. 
Apparently this already violates purity because rule #2 no longer holds true. 
It is impossible achieve purity without guaranteeing immutability. 
Note that, theoretically, it is still possible to write a pure program, but it is barely provable for sufficiently complex programs. 
Elixir is different, as it guarantees immutability.  
Nevertheless, it is impure, which can be observed easily when looking at how I/O is performed. 
Since it is implemented without the monad, performing I/O operations is impure.   
To sum up, of course, it is possible to write pure functions in both languages, but there is no guarantee other programmers do so as well. 
Furthermore both languages' compilers do not make use of the advantages purity can offer. 
As a consequence, pure functions in those languages are only beneficial for the programmer, because they are easier to reason about. 
Therefore I suggest writing pure functions wherever it is reasonable without obfuscating code, else sticking to the impure constructs the language was designed for. 

== Functional Programmer's Toolbox

Through the years a standard set of features for functional programming has been established. 
Though a multiparadigm language,  Go chose not to support any of those. 
Elixir in contrast, has them all baked in. 
So let us see, what in my opinion is a Toolbox making life in functional programming much easier. 

Pattern matching allows to define a function to behave differently depending on matched pattern. 
This helps to make code very concise. 
Take this function implementation, returning the length of a linked list in Elixir:

[source, elixir]
----

defmodule Length do
  def of([]), do: 0 //<1>
  def of([_ | tail]), do: 1 + of(tail) //<2>
end
----
<1> Matches the empty list. Returns 0
<2> Matches a list with more than 0 elements, destructuring the list into a head and tail. The head is first item of the list, which is not bound to a label in the example. The tail contains the rest of the list, which passed as an argument to the recursive call. 

The use of pattern matching helped avoiding a bunch of if-else statements making the code easily understandable and readable without clutter. 
The example already makes use of an advanced feature of pattern matching in Elixir. 
Elixir allows matching against all of its internal types plus user-defined types. 
Additionally, it is possible to destructure the data, as shown in the example,  where we split the list in its head and tail. 
Pattern matching is not only available in function signatures but also in other expressions. 
For instances inside the case statement:
[source, elixir]
----
case {1, 2, 3} do
  {4, 5, 6} ->
     "This clause won't match"
  {1, x, 3} ->
    "This clause will match and bind x to 2 in this clause"
  _ ->
    "This clause would match any value"
end
----

In addition to pattern matching Elixir features Guards, which are a way to add more complex constraints on patterns. 
Guards help to express an extended range of cases, where pattern matching on its own is not sufficient. 
Guards start with the *when* keyword and are followed by a boolean expression. 

[source, elixir]
----
def empty_map?(map) when map_size(map) == 0, do: true
def empty_map?(map) when is_map(map), do: false
----

Looking at the function empty_map? one might ask why guards are necessary since one can pattern match on maps, right? 
In fact, matching on maps is possible, but it is not possible to match an empty map. 
Hence guards are necessary here. 
Furthermore the guard *is_map(map)* demonstrates the fact, that a guard can restrict the matched types. 

The last feature I want to highlight is the pipe operator. 
The pipe is positioned in between two expressions. 
It takes the result of the left expression and passes it to the right. 
This allows to write more readable code, especially for people reading from left to right. 

[source, elixir]
----
String.split(String.upcase("No pipe sucks")) #-->["NO", "PIPE", "SUCKS"]

"Pipe rocks" |> String.upcase() |> String.split()  #-->["PIPE", "ROCKS"]
----

The pipe operator highlights the flow of information, which is from left to right. 
In contrast, the standard approach flows from the innermost function to the outermost. 

To summarize, Elixir provides neat features helping the functional programmer to be more efficient and write better code. 
Note that Elixir did not invent any of those features and therefore they can be found in some other languages as well. 
Nonetheless they are useful.   

== Standard Library & Collections

When considering a language for development the standard library and the language's ecosystem is a key aspect. 
In this chapter, we will inspect how many utilities the standard library of both languages provides from a functional perspective. 
Starting with Go, it has to be said, that the standard library is far from being as complete as Java's. 
It is kept very minimalistic offering barely more than a solid foundation to build upon. 
Due to the lack of parametric polymorphism, the standard library does not provide a broad range of container types. 
As a consequence Go does not provide the utilities for collection types a functional programmer is used to. 
The standard way of handling the absence is to write the needed helper functions yourself. 
Unfortunately, this has to be done for every type the operations should be applied on (assuming we want to avoid *interface{}* and casting for reasons discussed in chapter Type Systems).
This is pretty repetitive, leading to much boilerplate and code blocks where only types differ. 
As a consequence this kind of programming style, though very functional, is far from optimal in Go. 
Rob Pike, one of the language designers said about a map/reduce/filter package written by him: 

----
I wanted to see how hard it was to implement this sort of thing in Go, with as nice an API as I could manage. It wasn't hard.
Having written it a couple of years ago, I haven't had occasion to use it once. Instead, I just use "for" loops.

You shouldn't use it either.
----

Elixir is different in this aspect. 
A sufficient amount of generic Data types is baked into the language. 
Designed with functional programming in mind, the Enum module provides a programmer with higher order functions working on enumerable collection types.
The following demonstrates basic usage of the Enum module: 

[source, elixir]
----
range = [1, 2, 3, 4]
range |> Enum.map(fn x -> x * 2 end) #--> [2, 4, 6, 8]
      |> Enum.reduce(fn x, acc -> x + acc end) #--> 20
----

To summarize, Elixir fulfills the expectations a functional programmer has, with a standard library offering alot by default. 
Go is not build to hold up to those expectations, and does not provide more than a bare minimum. 
For a functional programmer the most standard tools are missing, which makes Go an unattractive language from this perspective. 

== Performance

Obviously different implementations of programming languages behave differently regarding performance. 
The same often holds true when implementing a feature in different paradigms within one language. 
Functional programming usually avoids mutation of state and thus encourages the use of recursion. 
However, this can result in a serious performance difference compared to imperative programming, depending on how the compiler/runtime optimizes the code. 
Thus this chapter will not compare Elixir and Go with each other but rather how the use of recursion vs imperative features affects a program's runtime. 

Elixir does not allow to mutate state and as such can not support any iterative control flow structures such as the *for* loop. 
Thus a programmer has to rely on recursion to get the job done. 
This means, a function is called recursively until a condition is reached, that stops the continuation.
A classic example is a function, that computes the nth-Fibonacci number. 
Where a Fibonacci Number is defined as:  

stem:[f_n = f_(n-1) + f_(n-2) forall n>2]

with the starting values:
stem:[f_0 = 0], 
stem:[f_1 = 1]

With the use of pattern matching a corresponding function in Elixir could look like the following:

[source, elixir]
----
def fibonacci(n) when n < 0, do: raise "Bad Boy! Fibonacci is defined only for n >= 0"
def fibonacci(0), do: 0
def fibonacci(1), do: 1
def fibonacci(n), do: fibonacci(n-1) + fibonacci(n-2)
----

The given implementation uses recursion for computing the Fibonacci number, whereas computing one Fibonacci number will always yield two function calls.
Since a Fibonacci number depends on its two predecessors, a cascade of function calls is necessary for computing a fibonacci number with a bigger n. 
Running this function naively without any optimizations applied is surely not optimal. 
Each function call results in a new stack frame, which is a lot of overhead for actually just passing around the called function's return value. 
A commonly applied optimization for functional languages is the so-called tail call optimization. 
This optimization can be applied when the last executed statement of a function is a function call. 
A recursive function that ends in a call to itself is called tail recursive. 
When the optimization is applied, the creation of new stack frames is avoided and the computation runs with constant stack space. 
Ultimately this results in a huge performance benefit. 
Elixir does provide this type of optimization, so let us use it. 
When looking at our naive Fibonacci implementation, the last executed statement is actually an addition. 
So we need to change the algorithm for computing the Fibonacci number.  

[source, elixir]
----
def fibonacci(n) when n < 0, do: raise "Bad Boy! Fibonacci is defined only for n >= 0"
#allows for a simple interface with arity 1, but dispatches the tailrecursion to a private implementation
def fibonacci(n), do: pfib(n, 1, 0)  
#defp defines a private (not visible for the outside world) function
defp pfib(0, _, result), do: result  
defp pfib(n, next, result), do: pfib(n-1, next+result, next) #Hooray! This is tail recursive!
----

When measuring execution times a huge difference between the two versions can be observed. 
I will just measure very roughly, as my goal is not to show absolute numbers, but the relative difference. 
The used method does not respect the times our program spent in kernel or user mode. 
But I suppose, when executing it a number of times it still has its relevance (in the end, you might just want to test it yourself!). 
I used the following: 

[source, elixir]
----
def timeFib(n) do
    start = :os.system_time(:seconds)
    fibonacciNumber = fibonacci(n)
    finish = :os.system_time(:seconds)
    timeTaken = finish - start
    IO.puts "#{n}-th Fibonacci number is: #{fibonacciNumber}. Computation finished in #{timeTaken} seconds!"
  end
----

The version with the naive implementation resulted in: 
----
45-th Fibonacci number is: 1134903170. Computation finished in 20 seconds!
----

The optimized version:
----
45-th Fibonacci number is: 1134903170. Computation finished in 0 seconds!
#No this is not a mistake - it was just that much faster!
----

As we can see, the difference is enormous. 
To sum up, even though elixir as a functional language relies on recursion only, it can be incredibly fast and efficient, when used correctly. 

Let us now have a look at how Golang handles things. 
Go, unlike Elixir, supports both iterative structures and recursion. 
Though, as of now, Golang does not support tail call optimization. 
Simply put, for computationally intensive tasks recursion should be avoided. 
Thus an efficient function must be iterative in Go. 
The performance difference between the recursive and iterative approach is comparable to the optimized and unoptimized versions used with Elixir. 
Based on this observation it can be concluded, that it is not reasonable to use the purely recursive approach, often seen in functional programming, in Go. 

== Conclusion

As highlighted in the different chapters of this paper, functional programming for humans involves much more than functions only. 
Go describes itself as a multiparadigm language, which is undoubtedly true. 
However, among all examined aspects, Go was never doing well. 
In my humble opinion, the type system at this point in time is at best unsuitable for functional programming. 
In addition to the missing functional standard library components, the performance penalty when using recursion and missing language constructs lead to my conclusion, that Go is not a functional language and should not be used as such. 
This does not mean including some functional principles cannot lead to improvements, so I suggest still considering them. 
Since this paper can not cover everything, you might want to dig a little into reflection in Go. 
Some people used it to implement some functional features, which are more useable than those examined in this paper. 
Obviously using reflection has its own downsides, but decide for yourself. 
In contrast to Go, Elixir was doing pretty well in all categories. 
One of the negatives for me personally is the dynamic type system, as I prefer programming in statically typed languages. 
Aside from that Elixir gives the impression of providing a solid foundation for functional programming. 
Similarly to Go, this paper is far from covering all aspects for Elixir. 
It provides a few more helpful features you might want to discover. 
In the end, functional programming itself is a much broader topic and depending on how it is used, way more complicated. 
Feel free to dive into the realms of crazy abstractions and scary maths to find what else there is to see. 

[bibliography]
== Sources & Further Readings

- [[[LC, 1]]] Raúl Rojas, A Tutorial Introduction to the Lambda Calculus: + 
https://www.inf.fu-berlin.de/lehre/WS03/alpi/lambda.pdf
- [[[IM, 2]]] Alex Potanin, Johan ̈Ostlund, Yoav Zibin, and Michael D. Ernst, Immutability: + 
https://homes.cs.washington.edu/~mernst/pubs/immutability-aliasing-2013-lncs7850.pdf

Some helpful resources, that helped me getting started with Elixir: +
For getting started: https://elixir-lang.org/getting-started/introduction.html  +
Dense information: https://elixirschool.com/en/ +
Talk about Elixir's Type System: https://www.youtube.com/watch?v=JT0ECYZ9FaQ&t=1168s +

Some resources to get you started with Go: +
For getting started: https://tour.golang.org/welcome/1 +
Different perspective on Go and Functional Programming: https://www.youtube.com/watch?v=c8Fwb4KbVJM

Functional Programming in General: +
History of Functional Programming: http://www.cse.psu.edu/~gxt29//historyOfFP/historyOfFP.html +
Category Theory for Programmers (scary maths!): https://www.youtube.com/watch?v=I8LbkfSSR58&list=PLbgaMIhjbmEnaH_LTkxLI7FMa2HsnawM_&index=1 +
Haskell, for looking at a pure functional language: https://www.haskell.org/
